# Generated by Django 4.2.5 on 2023-09-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_problemsubmission_delete_group'),
        ('users', '0002_alter_user_baekjoon_id'),
        ('groups', '0003_alter_round_participants_alter_round_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_rounds', to='users.user'),
        ),
        migrations.AlterField(
            model_name='round',
            name='problems',
            field=models.ManyToManyField(blank=True, to='problems.problem'),
        ),
    ]
